{% set version = environ.get("GIT_DESCRIBE_TAG", "0.0.0").replace('v', '') %}

package:
  name: ipython_pg
  version: {{ version }}

source:
  path: ../

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - ipython
    - psycopg2
    - pandas

build:
  noarch: python

about:
  home: https://github.com/LAV-ESG/ipython_psql_extension
  license: GPL 3.0
  summary: 'small wrapper around psycopg2, to make data-anaylsis between SQL and the Jupyter Notebook more fuild'
  description: |
    This IPython extension is a small wrapper around psycopg2, to make data-anaylsis between SQL and the Jupyter Notebook more fuild. The module was written at the Energy Systems Group of ETHZ-LAV, where we use Postgres as our central data repository.